version: '3.9'
services:
    kavita:
        image: jvmilazz0/kavita:latest
        volumes:
            - ./manga:/manga
            - ./data:/kavita/config
        ports:
            - "5000:5000"
        restart: unless-stopped
