version: '3'

services:
  music-tag:
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    ports:
      - "8001:8001"
    volumes:
      - /Volumes/Emby/Docker/Musics:/app/media:rw
      - ./config:/app/data
    command: /start
    restart: always